workflows:
  android_debug:
    name: Android Debug APK
    max_build_duration: 60
    environment:
      node: 18
      java: 17
    cache:
      cache_paths:
        - ~/.gradle/caches
        - ~/.gradle/wrapper
        - node_modules
    scripts:
      - echo "Installing JS deps"
      - |
        if [ -f yarn.lock ]; then
          npm i -g yarn
          yarn install --frozen-lockfile
        else
          npm ci
        fi
      - chmod +x android/gradlew
      - cd android
      - ./gradlew clean
      - ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - ${CM_EMAIL}  