name: job_tracker
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  url_launcher: ^6.3.2
  webview_flutter: ^4.13.0

  sqflite: ^2.4.2
  path: ^1.9.1

  flutter_local_notifications: ^19.4.0
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/banner_1.png
    - assets/images/banner_2.png
    - assets/images/logo.png
    - assets/images/stripe.png
    - assets/images/spotify.png
    - assets/images/slack.jpg
    - assets/images/facebook.png
    - assets/images/dribbble.png
    - assets/images/canva.png
    - assets/images/no_result.png
    - assets/images/no_job.png
    - assets/images/no_notification.png

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Light.ttf
          weight: 200
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
          weight: 500

